FROM bitwalker/alpine-erlang:20.2.2

# Set environment variables
ENV MIX_ENV=prod

# Copy tarball release
ADD _build/prod/rel/blog/releases/0.0.1/blog.tar.gz ./

# Set user
USER default

# Set entrypoint
ENTRYPOINT ["./bin/blog"]
